---

- name: Check parameters
  fail:
    msg: "You should not have both pim_secret_id and pim_folder_id defined."
  when:
    - pim_secret_id is defined
    - pim_folder_id is defined

- name: Lookup single secret
  set_fact:
    pim_secret: "{{ lookup('thycotic_secret', secretId=pim_secret_id, wantlist=True) }}"
  when: pim_secret_id is defined

- name: Lookup folder secret
  set_fact:
    pim_secret: "{{ lookup('thycotic_secret', folderId=pim_folder_id, wantlist=True) }}"
  when: pim_folder_id is defined

- name: Make sure {{ destination_openshift_secret_path }} exists
  file:
    path: "{{ destination_openshift_secret_path }}"
    state: directory
  delegate_to: localhost

- name: Create secret files in {{ destination_openshift_secret_path }}
  template:
    src: "openshift_secret_template.yml.j2"
    dest: "{{ destination_openshift_secret_path }}/{{ item.value.secretId }}.yml"
  loop: "{{ pim_secret|dict2items }}"
  no_log: True
  delegate_to: localhost
