---

- name: Create secret files in {{ destination_openshift_secret_path }}
  template:
    src: "openshift_secret_template.yml.j2"
    dest: "{{ destination_openshift_secret_path }}/{{ item.value.secretId }}.yml"
  loop: "{{ pim_secret[namespace['metadata']['name']]|dict2items }}"
  #no_log: True
  delegate_to: localhost

- name: create some secrets in openshift
  k8s:
    state: present
    definition: "{{ lookup('template', 'openshift_secret_template.yml.j2') }}"
    api_key: "{{ lookup('file', '/var/run/secrets/kubernetes.io/serviceaccount/token') }}"
    #cert_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    ssl_ca_cert: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    host: "https://{{ lookup('env','KUBERNETES_SERVICE_HOST') }}:{{ lookup('env','KUBERNETES_SERVICE_PORT') }}"
  loop: "{{ pim_secret[namespace['metadata']['name']]|dict2items }}"
  #no_log: True
  delegate_to: localhost
